# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hashmap internal functions
#'
#' @title Hashmap internal functions
#'
#' @name internal-functions
#' @rdname internal-functions
#'
#' @aliases .left_outer_join_impl
#' @aliases .right_outer_join_impl
#' @aliases .inner_join_impl
#' @aliases .full_outer_join_impl
#'
#' @param x an external pointer to a \code{HashMap}
#' @param y an external pointer to a \code{HashMap}
#'
#' @details These functions are intended for internal use only; do not
#'   call them directly.
NULL

#' @rdname internal-functions
.left_outer_join_impl <- function(x, y) {
    .Call('hashmap_left_outer_join_impl', PACKAGE = 'hashmap', x, y)
}

#' @rdname internal-functions
.right_outer_join_impl <- function(x, y) {
    .Call('hashmap_right_outer_join_impl', PACKAGE = 'hashmap', x, y)
}

#' @rdname internal-functions
.inner_join_impl <- function(x, y) {
    .Call('hashmap_inner_join_impl', PACKAGE = 'hashmap', x, y)
}

#' @rdname internal-functions
.full_outer_join_impl <- function(x, y) {
    .Call('hashmap_full_outer_join_impl', PACKAGE = 'hashmap', x, y)
}

